# Generated by Django 5.2.14 on 2026-05-18 08:49

import account.models
import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_avatar_alter_user_bio_alter_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_status',
            new_name='account_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='last_update',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_avatar_path, validators=[account.validators.validate_avatar]),
        ),
    ]
