# Generated by Django 5.2.14 on 2026-05-18 12:16

import account.models
import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_profile_status_user_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=account.models.user_avatar_path, validators=[account.validators.validate_avatar]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to=account.models.user_poster_path, validators=[account.validators.validate_poster]),
            preserve_default=False,
        ),
    ]
