# Generated by Django 5.2.14 on 2026-05-31 16:52

import blog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_uuid', models.UUIDField(default=uuid.UUID('30f0681c-6fa3-4f01-9ccc-1dc66bcf116b'), editable=False, unique=True)),
                ('cover', models.ImageField(unique=True, upload_to=blog.models.blog_cover_path, verbose_name='Blog Image')),
                ('title', models.CharField(max_length=90)),
                ('body', models.TextField()),
                ('preview_body', models.CharField(editable=False, max_length=400)),
                ('status', models.CharField(choices=[('V', 'Verified'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
