# Generated by Django 5.2.14 on 2026-06-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogvote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogvote',
            old_name='status',
            new_name='type',
        ),
    ]
