# Generated by Django 5.2.14 on 2026-06-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogvote_author_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
